stages:
  data_cleaning:
    cmd: python src/data/data_cleaning.py
    deps:
    - data/raw/swiggy.csv
    - src/data/data_cleaning.py
    outs:
    - data/cleaned/cleaned_data.csv
  data_preparation:
    cmd: python src/data/data_preparation.py
    deps:
    - data/cleaned/cleaned_data.csv
    - src/data/data_preparation.py
    params:
    - Data_Preparation.random_state
    - Data_Preparation.test_size
    outs:
    - data/interim/test.csv
    - data/interim/train.csv
  data_preprocessing:
    cmd: python src/features/data_preprocessing.py
    deps:
    - data/interim/test.csv
    - data/interim/train.csv
    - src/features/data_preprocessing.py
    outs:
    - data/processed/test_trans.csv
    - data/processed/train_trans.csv
    - models/preprocessor.joblib
  train:
    cmd: python src/models/train.py
    deps:
    - data/processed/train_trans.csv
    - src/models/train.py
    params:
    - Train.LightGBM
    - Train.Random_Forest
    outs:
    - models/model.joblib
    - models/power_transformer.joblib
    - models/stacking_regressor.joblib
  evaluation:
    cmd: python src/models/evaluation.py
    deps:
    - src/models/evaluation.py
    - data/processed/train_trans.csv
    - data/processed/test_trans.csv
    - models/model.joblib
    outs:
    - run_information.json

  register_model:
    cmd: python src/models/register_model.py
    deps:
    - run_information.json
    - src/models/register_model.py
